### ISSUE TITLE
React Build Error - Failed to Minify

### ISSUE THREAD

**Issue by yuschick** [lufinkey/node-justwatch-api#4]
First, let me say thanks for this API. Super helpful.

I am using this in a Create React App and when I try running `yarn build` I receive the following error:

```
Failed to minify the code from this file:
./node_modules/justwatch-api/index.js:7
```

The error directs me to the React Docs which provide this information:

**npm run build fails to minify**
Some third-party packages don't compile their code to ES5 before publishing to npm. This often causes problems in the ecosystem because neither browsers (except for most modern versions) nor some tools currently support all ES6 features. We recommend to publish code on npm as ES5 at least for a few more years.

Any plans to update for this use case?

**Comment by lufinkey** [comment]
I don't exactly know what is ES5 or ES6 in my code. Could you elaborate on what's in the code preventing it from minifying? Is it the await/async stuff?

**Comment by lufinkey** [comment]
Are you still having this issue?

**Comment by yuschick** [comment]
@lufinkey I am not sure because I ended up switching to a different API and haven't really looked at the project since implementing that. You can close this. It's not holding anything up on my end.
